INSERT INTO Departamento VALUES ('d1', 'Produção', NULL, '12/05/2024');
INSERT INTO Departamento VALUES ('d2', 'Contabilidade', NULL, '02/07/2022');
INSERT INTO Departamento VALUES ('d3', 'Pessoal', NULL, '11/11/2023');
INSERT INTO Departamento VALUES ('d4', 'Computação', NULL, '04/01/2021');
INSERT INTO Departamento VALUES ('d5', 'Pesquisa', NULL, '05/12/2022');

INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'João Silva', 'Rua A, 123', 1000.00, NULL, 'd1');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Maria Santos', 'Avenida B, 456', 1500.00, NULL, 'd2');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'José Oliveira', 'Travessa C, 789', 2000.00, NULL, 'd3');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Ana Souza', 'Praça D, 321', 1800.00, NULL, 'd4');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Carlos Pereira', 'Alameda E, 654', 2500.00, NULL, 'd5');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Mariana Costa', 'Rodovia F, 987', 2200.00, 1, 'd1');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Paulo Rocha', 'Estrada G, 654', 1900.00, 2, 'd2');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Fernanda Almeida', 'Viela H, 321', 2100.00, 3, 'd3');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Ricardo Nunes', 'Largo I, 789', 2800.00, 4, 'd4');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Amanda Ferreira', 'Ponte J, 654', 1700.00, 5, 'd5');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Roberto Santos', 'Rua K, 321', 2400.00, 6, 'd1');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Camila Oliveira', 'Avenida L, 987', 2600.00, 2, 'd2');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Gustavo Lima', 'Praça M, 654', 2300.00, 3, 'd3');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Isabela Souza', 'Travessa N, 321', 2000.00, 4, 'd4');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Felipe Pereira', 'Alameda O, 987', 2100.00, 5, 'd5');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Patrícia Costa', 'Rodovia P, 654', 2700.00, 1, 'd1');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Marcos Rocha', 'Estrada Q, 321', 2300.00, 7, 'd2');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Luana Almeida', 'Viela R, 987', 1900.00, 3, 'd3');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Rodrigo Nunes', 'Largo S, 654', 2600.00, 9, 'd4');
INSERT INTO Empregado VALUES (Empregado_SEQ.NEXTVAL, 'Juliana Ferreira', 'Ponte T, 321', 2200.00, 5, 'd5');

UPDATE Departamento SET gerente = 1 WHERE coddep = 'd1';
UPDATE Departamento SET gerente = 2 WHERE coddep = 'd2';
UPDATE Departamento SET gerente = 3 WHERE coddep = 'd3';
UPDATE Departamento SET gerente = 4 WHERE coddep = 'd4';
UPDATE Departamento SET gerente = 5 WHERE coddep = 'd5';

INSERT INTO Projeto VALUES (Projeto_SEQ.NEXTVAL, 'Projeto 1', 'Campina Grande', 'd1');
INSERT INTO Projeto VALUES (Projeto_SEQ.NEXTVAL, 'Projeto 2', 'Fortaleza', 'd2');
INSERT INTO Projeto VALUES (Projeto_SEQ.NEXTVAL, 'Projeto 3', 'Natal', 'd3');
INSERT INTO Projeto VALUES (Projeto_SEQ.NEXTVAL, 'Projeto 4', 'Recife', 'd4');

INSERT INTO Alocacao VALUES (19, 1, 20);
INSERT INTO Alocacao VALUES (14, 2, 20);
INSERT INTO Alocacao VALUES (9, 3, 20);
INSERT INTO Alocacao VALUES (16, 4, 20);
INSERT INTO Alocacao VALUES (10, 1, 20);
INSERT INTO Alocacao VALUES (7, 2, 20);
INSERT INTO Alocacao VALUES (13, 3, 20);
INSERT INTO Alocacao VALUES (11, 4, 10);
INSERT INTO Alocacao VALUES (11, 1, 10);
INSERT INTO Alocacao VALUES (17, 2, 5);
INSERT INTO Alocacao VALUES (17, 3, 10);
INSERT INTO Alocacao VALUES (17, 4, 5);
INSERT INTO Alocacao VALUES (15, 1, 10);
INSERT INTO Alocacao VALUES (15, 2, 10);
INSERT INTO Alocacao VALUES (15, 3, 10);

INSERT INTO Dependente VALUES (1, 'Miguel Silva', 10, 'M');
INSERT INTO Dependente VALUES (1, 'Sara Silva', 5, 'F');
INSERT INTO Dependente VALUES (2, 'Lucas Santos', 8, 'M');
INSERT INTO Dependente VALUES (2, 'Carolina Santos', 12, 'F');
INSERT INTO Dependente VALUES (3, 'Gabriela Oliveira', 15, 'F');
INSERT INTO Dependente VALUES (4, 'Pedro Souza', 7, 'M');
INSERT INTO Dependente VALUES (4, 'Mariana Souza', 3, 'F');
INSERT INTO Dependente VALUES (5, 'Rafael Pereira', 17, 'M');
INSERT INTO Dependente VALUES (5, 'Carlos Pereira', 17, 'M');
INSERT INTO Dependente VALUES (5, 'Bianca Pereira', 10, 'F');
INSERT INTO Dependente VALUES (6, 'Laura Costa', 6, 'F');
INSERT INTO Dependente VALUES (9, 'Aline Nunes', 12, 'F');
INSERT INTO Dependente VALUES (10, 'Leonardo Ferreira', 9, 'M');
INSERT INTO Dependente VALUES (10, 'Julia Ferreira', 14, 'F');
INSERT INTO Dependente VALUES (11, 'Cristina Santos', 16, 'F');
INSERT INTO Dependente VALUES (11, 'Fernando Santos', 8, 'M');
INSERT INTO Dependente VALUES (15, 'Guilherme Pereira', 5, 'M');
INSERT INTO Dependente VALUES (17, 'Daniel Rocha', 3, 'M');
INSERT INTO Dependente VALUES (17, 'Vanessa Rocha', 7, 'F');
INSERT INTO Dependente VALUES (18, 'Ana Almeida', 12, 'F');
INSERT INTO Dependente VALUES (19, 'Luciana Nunes', 8, 'F');
INSERT INTO Dependente VALUES (19, 'Bruno Nunes', 11, 'M');
INSERT INTO Dependente VALUES (20, 'Patricia Ferreira', 4, 'F');
INSERT INTO Dependente VALUES (20, 'Renato Ferreira', 10, 'M');